# **Quizz de Poo**

In [38]:
import numpy as np

class Formulas:
    def __init__(self):
        # Inicialización básica de la clase madre.
        super().__init__()

class TrianguloEquilatero(Formulas):
    def __init__(self, lado):
        super().__init__()  # Asegura la inicialización adecuada con la clase madre.
        self.lado = lado

    def calcular_area(self):
        # Calcula la altura y luego el área del triángulo equilátero.
        altura = (np.sqrt(3) / 2) * self.lado
        return (self.lado * altura) / 2

    def calcular_perimetro(self):
        return 3 * self.lado

class TransformarMatriz(Formulas):
    def __init__(self, lista):
        super().__init__()  # Asegura la inicialización adecuada con la clase madre.
        self.lista = lista  # Asume que la lista ya es de tamaño adecuado (16 elementos).

    def transformar(self):
        # Directamente intenta transformar la lista en una matriz 4x4.
        return np.array(self.lista).reshape(4, 4)

class CalcularDeterminante(Formulas):
    def __init__(self, matriz):
        super().__init__()  # Asegura la inicialización adecuada con la clase madre.
        self.matriz = matriz

    def determinante(self):
        return (np.linalg.det(matriz))







In [35]:
# Crear una instancia de TrianguloEquilatero con un lado de longitud l
lado = 5  # Ejemplo con lado de 5 unidades
triangulo = TrianguloEquilatero(lado)

# Calcular el área
area = triangulo.calcular_area()
print(f"Área del triángulo equilátero: {area}")

# Calcular el perímetro
perimetro = triangulo.calcular_perimetro()
print(f"Perímetro del triángulo equilátero: {perimetro}")


Área del triángulo equilátero: 10.825317547305481
Perímetro del triángulo equilátero: 15


In [36]:
# Lista de 16 elementos
lista = [i for i in range(1, 17)]  # Ejemplo con números del 1 al 16

# Crear una instancia de TransformarMatriz con la lista
transformador = TransformarMatriz(lista)

# Transformar la lista en una matriz 4x4
matriz = transformador.transformar()
print("Matriz 4x4 resultante:")
print(matriz)


Matriz 4x4 resultante:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [41]:



calculador = CalcularDeterminante(matriz)


determinante = calculador.determinante()
print(f"Determinante de la matriz: {determinante}")


Determinante de la matriz: 0.0
